### ISSUE TITLE
suggestion IsNotEmptyOrWhiteSpace for strings

### ISSUE THREAD

**Issue by FutureTD** [danielwertheim/Ensure.That#102]
There are situations when a string can be null, but if is not null, you don't want it to be a empty string or contain whitespace only.

These are pretty common is constructors and methods with default parameters.

so I propose EnsureArg.IsNotEmptyOrWhiteSpace. If the string is null it would not throw. However, If the string is not null, but is empty or white space only, It would.

**Comment by ndrwrbgs** [comment]
I'm not sure how common this use case would be - I believe the reason the BCL uses `string.IsNullOrEmpty()` or `string.IsNullOrWhiteSpace()` to provide a super-set of `null` in scenarios where `null` and `string.Empty` are not easily distinguishable. Could you try to contrive a few use cases outside of the one you have in mind that would use this for better understanding of the problem space as you understand it?

The reason I ask is that the usage scenario here can be satisfied by 
```C#
void My_IsNotEmptyOrWhiteSpace(string input) {
  if (input != null) {
    EnsureArg.String.IsNotNullOrWhiteSpace(input, nameof(input));
  }
}
```
without a modification to the library, which if the applicable usages are narrow then a work-around would be advisable rather than a change.

**Comment by danielwertheim** [comment]
Released
