### ISSUE TITLE
Suggestion: HasNoNull on collections

### ISSUE THREAD

**Issue by seroche** [danielwertheim/Ensure.That#105]
Hi,

I want to make sure that my collections do not contain null values. It would great to get a new extension method that would 
- go through all elements 
- throw an exception if they are null.

**Comment by ndrwrbgs** [comment]
I'm going to add this to #71

**Comment by ndrwrbgs** [comment]
Also implemented in the -Experimental library

**Comment by danielwertheim** [comment]
@ndrwrbgs what's preventing from bringing it into this repo?

**Comment by ndrwrbgs** [comment]
_I definitely replied to this in my email client, but it looks like it never went through :(._

Nothing at all, if you want it here! I had 2 goals in implementing it externally
1) faster Time To Market (didn't have to match style :-P selfishly)
2) demonstrating to others such as @seroche how extensible the existing library is for individual use cases (the primary factor for incorporating into the library at this point I think would be features that are applicable to the widest group of users [e.g. "everyone who uses this will want X"])

**Comment by ndrwrbgs** [comment]
Replying to the feature request itself, I have one main concern

Should this be a [Conditional("DEBUG")] method, or documented heavily to expect users to do
```C#
#if DEBUG
#endif
```

The concern being an extra enumeration over every item in a collection on common code paths (e.g. the 'happy path' this enumeration is pointless, but very often when taking a collection we expect [ItemNotNull] [link](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ItemNotNullAttribute)). Essentially, we _normally_ expect this to be a waste, and enumerables can be expensive in some code paths so I wouldn't want to 'encourage' users to enumerate them many times. The `Ensure.That` library so far does consider performance pretty forefront (e.g. how #113 would make a very nice usability improvement, but a big degradation in performance versus normal `if null throw` semantics).

Now, more pragmatically, I see 2 things.
1) Okay but that might be micro-optimizing, especially given it's a 'Collection' we are already asserting (softly, but by convention) that it's "in memory", so enumeration should not be (relatively) expensive
2) If the item should NOT contain nulls, can we use a data type that does not allow it? E.g. instead of relying on argument validation (obviously there are cases where we don't control the caller, which would necessitate validation) we never allow a .Add call to complete with `null`
    i) In those cases that we don't control the caller, a possible 'optimized validation mode' would be to do something like wrap up the input object in a new object type (beyond scope of `Ensure.That`) that throws a proper ArgumentException if DURING ENUMERATION it sees a null, this prevents the multiple enumerations of the data source, but also allows the "oops, that's null" exception.
