### ISSUE TITLE
Create an AggregateException, or throw a single exception from a list of EnsureArg failures.

### ISSUE THREAD

**Issue by grleachman** [danielwertheim/Ensure.That#134]
I'd like to use EnsureArgs to check all my arguments in the constructor, and throw a single Exception to report on all issues.

eg.
```
public CelebratePiDay(bool isHomeMade, bool isPie, bool isPiDay)
{
  Ensure(
    Ensure.Bool.IsTrue(isHomeMade, nameof(isHomeMade)),
    Ensure.Bool.IsTrue(isPie, nameof(isPie)),
    Ensure.Bool.IsTrue(isPiDay, nameof(isPiDay)),
  )
}
```
```
var piCelebration = new CelebratePiDay(false, true, false);
```

which throws  a single exception of "isHomeMade is false, isPiDay is false", or an AggregateException.

**Comment by danielwertheim** [comment]
Any ideas on the construct of it? E.g. acting on `params Action[]` and try-catch and then re-throw single exception if exactly one or all in `AggregateException` if more than one? If that would be the solution I'm not sure if it should be in Ensure.That or if it's better to have in application as a simple construct. Need to measure performance of it first.

**Comment by ndrwrbgs** [comment]
I really like this idea, it helps developers avoid the hunt-and-peck when there are multiple failures!
I'd want to be careful with the performance though. Action[] could be easily wrapped on top of the existing APIs, but would be the least performant. A new semantic that doesn't throw on violations but can return an error code to be aggregated would allow for the best performance -- but the most noise to the existing code.

@grleachman are you hosted in a scenario where 1) these checks have to be in your production code (e.g. no #if DEBUG tricks for us) and 2) performance is SUPER critical that you have to avoid object allocations?

**Comment by grleachman** [comment]
no #if DEBUG. This is production code. 
Performance is critical. We use them in the constructors of all Dto's so it's exceptionally sensitive.

**Comment by ndrwrbgs** [comment]
With performance being critical, the way this is falling in my head would require a major rework of the library (a duplication of every validation we have that can track validation errors in some collection rather than throw, and would have to avoid using Action or Func anywhere as those provide allocations not possible to use in performance-critical code).

Ideally what would happen here, if everyone agreed this was worth the impact to the code, is we would hide all validation currently in Ensure.That behind another layer of abstraction s.t.

Ensure.That().Assertion() -> RunAssertion[s](); if (any) { throw }
Ensure.ManyThings(Assertion, Assertion) -> RunAssertion[s](); if (any) { throw aggregate }

This would result in code dedupe, but worse performance for existing users of Ensure.That().Assertion() [though, minorly worse, we are not talking order of magnitude].

As I'm not personally vested in the gain of it at this time it's not the kind of refactor I can take on. I'd encourage @grleachman to first implement and try a solution like below, and see if the performance overhead is really too much (I know it would be for my work-product, but we operate without allocations like C++-code-on-C#, and you may get lucky that the overhead add is negligible in your system)

```CSharp
public static void EnsureMany(params Action[] /* some tricks with closures you can do by making this Func that can support compiling to argumentless methods rather than capturing an object, but complicates the code here so omitting */ validations)
{
  var exceptions = validations.Select(act => try { act(); return null; } catch(Exception e) { return e; })
    .Where(ex => ex != null)
    .ToArray();
  if (exceptions.Any()) throw new AggregateException(exceptions);
}
```

I'm hoping the performance sensitivity is less than we might assume and we can get lucky with this solution working for you.

**Comment by ndrwrbgs** [comment]
In the happy case, this has no exceptions, and only is allocating objects for the Actions. I _vaguely_ recall you might be able to avoid those if you take everything you need as an input (as opposed to capturing it in a "closure" -- e.g. `EnsureMany(T arg, Action<T> action1, Action<T> action2 /* enumerating prevents the array allocation of params */)`) If you unwrap the LINQ also it could end up meeting performance concerns as well, IFF we assume the violations are rare. If it were going into the library code here though I'd want to avoid that assumption and make failure case cheap too.

**Comment by danielwertheim** [comment]
Would we "gain" from e.g. making a bunch of `EnsureMany<T1, T2>` `EnsureMany<T1, T2, T3,..>` a'la Tuple style and at one point just offer the `params` construct?

**Comment by ndrwrbgs** [comment]
Not fully ingesting what you're suggesting, the shape of the API would
still require major refactors.

**Comment by ndrwrbgs** [comment]
This keeps coming to my mind, after seeing FluentAssertions have the same functionality.
I think we could do it with a (pretty major, but mostly mindless) refactor that made the code expose 'What to do on violation' flag as opposed to just an `Exception` hook (which must always throw).

Then it'd be pretty easy to code up [even as a separate library plugin-based to this one] an `AsyncLocal` `Stack` of `ValidationContexts` and have OnError look to see if it's in one of those -- if it is add to a list and if not do normal throw. Then when `ValidationContexts` (name should be redone) is `IDispose()d` it would throw the collection.

This is just one possible implementation, but it makes a route by which the library could make a decently generic change (refactoring from ExceptionFactory to OnError could be done unbreakingly and could provide use beyong this feature request) and also this could be supported (even external to the main library)
