### ISSUE TITLE
EnsureArg.IsNotNull without class requirement

### ISSUE THREAD

**Issue by cjvanwyk3** [danielwertheim/Ensure.That#140]
Would it be possible to remove the class requirement on EnsureArg.IsNotNull?  Maybe something like this:
        public static T IsNotNull<T>(T value, string paramName = null)
        {
            var type = typeof(T);
            if ((type.IsClass || IsNullable(type)) && value == null)
            {
                throw new ArgumentNullException(paramName, "Value may not be null.");
            }

            return value;
        }

        private static bool IsNullable(Type type) => Nullable.GetUnderlyingType(type) != null;

**Comment by danielwertheim** [comment]
Is this the case you want to support? E.g. a nullable int.

```csharp
[Theory]
[InlineData(null)]
public void ShouldThrow_WhenNull(int? i) =>
    ShouldThrow<ArgumentNullException>(
        ExceptionMessages.Common_IsNotNull_Failed,
        () => Ensure.Any.IsNotNull(i, ParamName),
        () => EnsureArg.IsNotNull(i, ParamName),
        () => Ensure.That(i, ParamName).IsNotNull());

[Theory]
[InlineData(1)]
public void ShouldNotThrow_WhenNull(int? i) =>
    ShouldNotThrow(
        () => Ensure.Any.IsNotNull(i, ParamName),
        () => EnsureArg.IsNotNull(i, ParamName),
        () => Ensure.That(i, ParamName).IsNotNull());
```

![image](https://user-images.githubusercontent.com/196044/81468590-cc080180-91e0-11ea-87bf-3388c8f47e42.png)

**Comment by ndrwrbgs** [comment]
It's worth noting that a `struct` cannot be `null` in C#. It can override `.Equals` to return `true` when compared to `null`, but it itself cannot be `null` - so I'd be cautious about the API exposed if any changes are needed for this.

int? a = null; is `Equal` to `null`, but is not actually `null`.

**Comment by danielwertheim** [comment]
The code above are tests against existing code.

**Comment by ndrwrbgs** [comment]
I apologize for my silliness thanks Daniel for the patience!
@cjvanwyk3 are you still blocked on this?

**Comment by cjvanwyk3** [comment]
What I'm ultimately after is being able to use EnsureArg on a generic that does not have a class requirement.  For example

// This will not work.
        public void GenericMethod<T>(T parameter)
        {
            EnsureArg.IsNotNull(parameter);
        }

**Comment by ndrwrbgs** [comment]
So sorry to have dropped this!

@cjvanwyk3 could you refactor your code to match more like what we have here under AnyArg?
https://github.com/danielwertheim/Ensure.That/blob/73c566430ecbc7fa77a54b30e4000d7cc39e9cf1/src/projects/EnsureThat/Enforcers/AnyArg.cs#L8-L26

The thing is, we don't have an overload that checks != null in the case that '== null' is impossible. I'm trying to find a way that it makes sense in the general (I 100% relate to your use case), but am struggling to generalize it to everyone.

One work around that's always available as you want things that aren't in the base library (although thank you for asking since it helps improve coverage ♥) is that the Ensure.That() syntax returns a Param<> object you can write any extension method imaginable against. So even if a particular case doesn't make it into the code base, it can still be supported for your style!

**Comment by cjvanwyk3** [comment]
@danielwertheim Thank you so much!  The EnsureArg.HasValue(item); works great for us!
