### ISSUE TITLE
.NET Core framework update needed.

### ISSUE THREAD

**Issue by MrZoidberg** [danielwertheim/Ensure.That#25]
Hi,

My app uses a recently released .NET Core 1.0 and it cannot compile with Ensure.That because of the different framework name:

>  The dependency Ensure.That 4.0.0 does not support framework .NETCoreApp,Version=v1.0.

Could you please add netcoreapp1.0 to the list of supported frameworks?

**Comment by danielwertheim** [comment]
It's supported just not deployed. You can try with master branch if urgent.
Should be able to pull and run the build script. Then use the produced
Nuget. Or use dotnet CLI.

On 5 Oct 2016 15:19, "Mikhail Merkulov" <notifications@github.com> wrote:

Hi,

My app uses a recently released .NET Core 1.0 and it cannot compile with
Ensure.That because of the different framework name:

The dependency Ensure.That 4.0.0 does not support framework
.NETCoreApp,Version=v1.0.

Could you please add netcoreapp1.0 to the list of supported frameworks?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danielwertheim/Ensure.That/issues/25>, or mute the
thread

**Comment by danielwertheim** [comment]
Try this https://www.nuget.org/packages/Ensure.That/5.0.0-b3

**Comment by MrZoidberg** [comment]
It works, thanks!
