### ISSUE TITLE
Ensure.That Func<T> where T : class issue

### ISSUE THREAD

**Issue by Aszan** [danielwertheim/Ensure.That#30]
Add new one to deal with `null` case:
```C#
public static Param<T> That<T>(Func<T> expression, string name = "")
{
    return new Param<T>(name, expression?.Invoke());
}
```

**Comment by danielwertheim** [comment]
The `Ensure.That` API is being marked as obsolete in v7 and I'm not following which case the above will solve as you should pass an expression. More correct would be to throw an exception if `expression` is null.

Closing due to the fact that this API is going to be removed in v8. Feel free to re-open if you feel I'm missing something.
